name: Dev

on:
  push:
    branches:
      - main
      - dev
      - staging
  pull_request:
    branches:
      - main
      - dev
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4.1.7

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            lucasnogueira1325/ese-auth:v1
            lucasnogueira1325/ese-calorieservice:v1
            lucasnogueira1325/ese-foodgroup:v1
            lucasnogueira1325/ese-dailycalories:v1
          
  deploy_dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Deploy to Development
        run: echo "Deploying to Development"

  deploy_staging:
    needs: deploy_dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging"

  deploy_prod:
    needs: deploy_staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production"
